version: '3.9'

services:
  service:
    container_name: service
    image: service:0.0.1
    restart: always
    depends_on:
      - resistance-db
    environment:
      JDBC_URL: jdbc:postgresql://resistance-db:5432/resistance_db
      JDBC_USER: postgres
      JDBC_PASSWORD: sa
    ports:
      - "8086:8080"
  bot:
    container_name: bot
    image: bot:0.0.1
    restart: always
    depends_on:
      - service
    environment:
      TELEGRAM_API_KEY: <token>
      TELEGRAM_WEBHOOK_URL: <hook_urk>
      SERVER_URL: http://service:8080/
    ports:
      - "8085:8081"
  resistance-db:
    container_name: resistance-db
    image: postgres:11
    environment:
      POSTGRES_DB: resistance_db
      POSTRGRES_USER: postgres
      POSTGRES_PASSWORD: sa
    ports:
      - "5433:5432"