version: '3.1'

services:
  service:
    container_name: service
    image: service:0.0.1
    restart: always
    depends_on:
      - resistance-db
    environment:
      - JDBC_URL=${JDBC_URL}
      - JDBC_USER=${POSTGRES_USER}
      - JDBC_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 8086:8080
  bot:
    container_name: bot
    image: bot:0.0.1
    restart: always
    depends_on:
      - service
    environment:
      - TELEGRAM_API_KEY=${API_KEY}
      - TELEGRAM_WEBHOOK_URL=${WEBHOOK_URL}
      - SERVER_URL=${SERVER_URL}
    ports:
      - 8085:8081
  resistance-db:
    container_name: resistance-db
    image: postgres:11
    environment:
     - POSTGRES_DB=${POSTGRES_NAME}
     - POSTRGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5433:5432